### ISSUE TITLE
Provide constants for activity types

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#10]
while the event types can be accessed as String constants (TaskListener.CREATE), the activities (userTask, startEvent, ...) can't. It would make implementing selectors much easier if we had a constant class.

I would suggest that we start with those constants within this extension but aim to have those in camunda core soon.

**Comment by jangalinski** [comment]
I would prefer enums for all possible elements to have typesafe control. We could also define scopes on those enums to ensure that no unsupported eventlisteners get registered for a type. 

I would need a complete list of all bpmn and cmmn elements (userTask, serviceTask, humanTask, ...). Any idea where I could get such a list (hopefully automated)?

**Comment by saig0** [comment]
I think automation is not required here, you can look at the class [BpmnParse](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java) and list all elements when the listener is called.

**Comment by bentrm** [comment]
You may be aware of this, but I was stumbling over similar (unresolved) efforts in core looking for an enum helper:
* [ActivityTypes.java](https://github.com/camunda/camunda-bpm-platform/blob/7294e11b4ce55df37f716d452ef768597536aaad/engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/ActivityTypes.java)
* [Open issue](https://app.camunda.com/jira/browse/CAM-3385)
