### ISSUE TITLE
Does canumda workflow engine support reactive programming ?

### ISSUE THREAD

**Issue by shyding** [camunda/camunda-bpm-reactor#110]
Does canumda workflow engine support reactive programming ?

**Comment by shyding** [comment]
Does camunda support webflux and spring data r2dbc ?

**Comment by jangalinski** [comment]
Even when you run Camunda with spring boot, it internally uses mybatis for ORM, so I see no way to achieve this. The zeebe.io "follow up" version Camunda should be able support reactive programming.
