### ISSUE TITLE
Rename extension, update assets & documentation

### ISSUE THREAD

**Issue by celanthe** [camunda/camunda-bpm-reactor#119]
Hi all,

I hope today finds you well! This issue is being opened to ask if you would be open to renaming your extension on GitHub to reference Camunda Platform 7 rather than Camunda BPM after its release on April 12th, 2022. (For example: camunda-platform-7-graphql) This change will also likely impact any screenshots you have in the README that reference Camunda BPM or previous versions of Camunda Platform, and this will likely need to also be updated throughout the repo's documentation as a whole. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with. 

While it is not a **requirement** that you rename your extension to align with Camunda Platform 7, we would **greatly** appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

 if you have any questions or require any assistance, please do not hesitate to reach out to @camunda-community-hub/devrel! :)

**Comment by akeller** [comment]
@jangalinski @saig0 is this something you are interested in updating?

**Comment by jangalinski** [comment]
I renamed the repo and added the C7 badge. Nothing more I like to do as I abandoned this project (for good reasons, see note in README) ... I suppose if no maintainer shows up in the next weeks/months you should archive this.

Is was a great project, it has lots of stars ... but it uses outdated and unmaintained libraries to function ... I can't keep up with this (and use spring boot eventing myself ...)

**Comment by berndruecker** [comment]
Thanks a lot for renaming - I will go ahead and archive it. It had its time :-)
