### ISSUE TITLE
TaskListeners are always registered for UserTasks 

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-bpm-reactor#17]
Since a task listener can only be invoked for a user task, it should be registered for user tasks automatically. So I don't need to set the type to 'userTask' explicit.

**Comment by jangalinski** [comment]
question regarding cmmn: is this also a userTask, or do we have to consider case(human)Tasks?

**Comment by saig0** [comment]
You're right. For CMMN, the listener must be registered for 'humanTask'.

**Comment by jangalinski** [comment]
If we do not need to separate listeners for bpmn and cmmn on element level, we could just register humanTask as userTasks internally by simple replacement. We would use a common identifier for both. Objections?

**Comment by saig0** [comment]
I agree that you can use the same mechanism for both. For me it's important that the user should not write 'userTask' or 'humanTask' to register the listener.

**Comment by jangalinski** [comment]
registering a tasklister automatically set the selector context to "task", fixed together with #16.
