### ISSUE TITLE
Set up CI environment

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#23]
we should have automatic builds at least of the master branch  and publishing of the snapshot artifacts

**Comment by saig0** [comment]
I created a job on camunda CI: https://app.camunda.com/jenkins/view/cam-community/job/community-extension-camunda-bpm-reactor/

The build is deployed to camunda Nexus: https://app.camunda.com/nexus/#nexus-search;quick~camunda-bpm-reactor

Is it ok?

**Comment by jangalinski** [comment]
Do I have access to the jenkins? Anyway: I can see the artifact, so its looking good. Thanks.
It already broke our project build :-)

**Comment by saig0** [comment]
@jangalinski: only camunda have access to jenkins but I register your email address so that you will receive mails if the build fails.
