### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#25]
I think we are good to go!

@saig0 can you please take over?

Release version: 1.0, next dev version: 1.1-SNAPSHOT.

**Comment by saig0** [comment]
@jangalinski: done!

**Comment by meyerdan** [comment]
Will there be a blogpost?

**Comment by jangalinski** [comment]
Well, I think I will mention it on holisticon.de anyway, should I provide an english version for camunda.org? Or will you take over, @saig0 ?

**Comment by meyerdan** [comment]
Jan, you can provide a pull request to https://github.com/camunda/blog.camunda.org The README mentions how to write a post.

It would be really to cool to have a "guest post" on there.

**Comment by jangalinski** [comment]
I do not see the release on maven central. Did something go wrong?

**Comment by meyerdan** [comment]
@hawky-4s- ?

**Comment by jangalinski** [comment]
Reopen, still no visible artifacts ...

**Comment by hawky-4s-** [comment]
Sorry, currently doing many things simultaneously. I released the staging repository few minutes ago. Takes some hours till it can be found through search but it is already there:

[https://oss.sonatype.org/content/repositories/releases/org/camunda/bpm/extension/](https://oss.sonatype.org/content/repositories/releases/org/camunda/bpm/extension/)
