### ISSUE TITLE
use camunda 7.6.0

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#32]

**Comment by bentrm** [comment]
Is this still an issue? I'm using it with 7.5.0 and didn't have any problems with it? Something I need to be aware of?

**Comment by jangalinski** [comment]
Ist not that 7.5 wont work. Ist a reimender issue to always Support the lastest version "officially" by Building against 7.5

**Comment by jangalinski** [comment]
fixed with 793cb8dbc6d9b1b68843136198e9da23e6b1c861
