### ISSUE TITLE
I'd like to try my hand at the spring integration

### ISSUE THREAD

**Issue by rmoskal** [camunda/camunda-bpm-reactor#35]
I think a little explanation, in broad terms, of what needs doing, would get me there. Any interest?

**Comment by jangalinski** [comment]
Yes of course. I think there is not too much to do. Create a new module under extension (camunda-bpm-reactor-spring) that uses the core.
This module should basically provide a camundaEventBus (and the wrapped eventBus) via Configuration class. So when I want to use the extension with spring, I do not have to provide my own configuration.
Based on this, it would be a good idea to additionally provide a way to enrich a given processEngineConfiguration with the plugin. I am not yet sure what the best way would be. Maybe you have an idea?

**Comment by jangalinski** [comment]
Hi rmoskal ... I had a few moments and started implementing the spring extension ... and now its finished. That does not interfer with work you already did. Checkout the PR, I will merge it tomorrow after some rest+review.
