### ISSUE TITLE
release 1.2

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#37]
we really could use the spring extension as soon as possible, I think its worth a release. So once #36 is merged, it would be great if someone could take over.

Release version: 1.2
new dev versin: 1.3-SNAPSHOT

**Comment by saig0** [comment]
done :)

**Comment by jangalinski** [comment]
Thanks ... you were fast this time ... the colleagues are having trouble with the spring integration ... I gonna open a bug and prepare a fix :-)
