### ISSUE TITLE
Failing test - InterruptingErrorEventTest

### ISSUE THREAD

**Issue by yanavasileva** [camunda/camunda-bpm-reactor#58]
Hello,

Camunda extension jenkins job is failing because of the `InterruptingErrorEventTest `(recently added)

`Delegate Expression 'serviceDelegate' did neither resolve to an implementation of 'interface org.camunda.bpm.engine.impl.pvm.delegate.ActivityBehavior' nor 'interface org.camunda.bpm.engine.delegate.JavaDelegate'.`

I am attaching the log. If you have any questions please let me know.

[failed_InterruptingErrorEventTest.txt](https://github.com/camunda/camunda-bpm-reactor/files/1336442/failed_InterruptingErrorEventTest.txt)

**Comment by jangalinski** [comment]
I guess this is no longer relevant
