### ISSUE TITLE
Shared-Environment integration

### ISSUE THREAD

**Issue by eberhardmayer** [camunda/camunda-bpm-reactor#59]
Hi Extension-Provider,

is it possible to deploy this Engine-Plugin in a shared environment on a tomcat?

Greetings
Eberhard Mayer

**Comment by jangalinski** [comment]
Sorry for the late answer ...  did you try to do so? shared/tomcat is not my current domain. In general, it should work since it is "just" a process engine plugin ... but you would have to take care of providing all required 3rd party dependencies globally ...
