### ISSUE TITLE
snapshot release to camunda-bpm-community-extensions-snapshots

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-reactor#68]
currently, I see only 1.5.0-SNAPSHOT, not 2.0.0 ...

why?

**Comment by hawky-4s-** [comment]
Please check again. There was an issue on the old machine which used an old incompatible maven version.

**Comment by jangalinski** [comment]
thanks!

**Comment by carlosjourdan** [comment]
I think this issue has come back. Adding the dependency to 2.0.0-SNAPSHOT results in a missing artifact error... am I missing something?
