### ISSUE TITLE
No eventBus found

### ISSUE THREAD

**Issue by carlosjourdan** [camunda/camunda-bpm-reactor#70]
I'm trying to use camunda-bpm-reactor with the springboot starter, but when I try call `CamundaReactor.eventBus()` I get an IllegalStateException with the message "No eventBus found. Make sure the Reactor plugin is configured correctly.".

Here is the outline of my setup:

Application:

```
@SpringBootApplication
@EnableProcessApplication
public class CamundaWebapp {

  public static void main(String... args) {
    SpringApplication.run(CamundaWebapp.class, args);
  }

}
```

Configuration:

```
@Configuration
public class ProcessEngineConfiguration {

	@Bean
	public static ProcessEnginePlugin myPlugins()
	{
		return CamundaReactor.plugin();
	}
}
```

Listener:

```
@CamundaSelector(type = "intermediateThrowEvent", event = ExecutionListener.EVENTNAME_START)
@Component
public class MyExecutionListener implements ExecutionListener{
	
        public MyExecutionListener()
        {
 		CamundaReactor.eventBus().register(this);
        }	

	@Override
	public void notify(DelegateExecution execution) throws Exception {
		System.out.println("GOTCHA");
	}

}
```

From the logs it would seem that the plugin is activated:

> 2017-12-02 13:45:41.241  INFO 15384 --- [           main] org.camunda.bpm.engine.cfg               : ENGINE-12003 Plugin 'CompositeProcessEnginePlugin[genericPropertiesConfiguration, camundaProcessEngineConfiguration, camundaDatasourceConfiguration, camundaJobConfiguration, camundaHistoryConfiguration, camundaMetricsConfiguration, camundaAuthorizationConfiguration, CreateAdminUserConfiguration[adminUser=AdminUserProperty[id=demo, firstName=Demo, lastName=Demo, email=demo@localhost, password=demo]], enterLicenseKeyConfiguration, failedJobConfiguration, CreateFilterConfiguration[filterName=All], **ReactorProcessEnginePlugin**, disableDeploymentResourcePattern]' activated on process engine 'default'

But still I get the error. Any ideas?

**Comment by carlosjourdan** [comment]
Found out that the problem has to do with `CompositeProcessEnginePlugin`. Seems to be fixed in master branch, I was having trouble because I was using version 1.2.

Btw, this brings me back to issue #68

**Comment by jangalinski** [comment]
what do you mean with #68?  To my knowledge, 2.0.0-SNAPSHOTS are built, see https://app.camunda.com/nexus/content/repositories/camunda-bpm-community-extensions-snapshots/org/camunda/bpm/extension/reactor/
