### ISSUE TITLE
Possible to use reactor in separate webapp?

### ISSUE THREAD

**Issue by somejavadev** [camunda/camunda-bpm-reactor#82]
Hi,  
I currently have the standard Camunda 8.7.0 download with tomcat. What I would like to know if is it possible to create a separate spring boot app deploy it to that tomcat and register the camunda-bpm-reactor within this spring boot app to listen in on events?  

Currently in my separate spring boot app I retrieve Camunda's process engine via JNDI , add the CamundaReactor.plugin() to the process engines configuration ``configuration.getProcessEnginePlugins().add(CamundaReactor.plugin());`` and then create the event bus ``CamundaEventBus eventBus = CamundaReactor.eventBus();`` I then have a listener ``@CamundaSelector
public class TestCaseListener implements CaseExecutionListener {`` which I expect to receive the events.
    
This is currently not working. Is there a way to hook into the events from the standard Camunda tomcat? I would like to log certain events to a separate database for auditing.

**Comment by jangalinski** [comment]
This is not a remote messaging solution, all events are passed synchronously and in memory. Due to the nature of the camunda context intsnaces (delegateExecution, delegateTask), communication can not be remote or async.
