### ISSUE TITLE
How can I config a listener for variables update ?

### ISSUE THREAD

**Issue by Himly1** [camunda/camunda-bpm-reactor#92]
Hello, At the first thanks you for your framework.
In my case I need to synchronize variables of process instances to my db.

For to do that I want to config a listener for variables update.
So my question is camunda-bpm-reactor is support to config  listener of  variables update  ?

Thank you very much.

**Comment by jangalinski** [comment]
so far this extension does not support variable listeners ... not sure if this is possible, will have to investigate

**Comment by jangalinski** [comment]
There is no variable change listener mechanism in place for BPMN in camunda, so there is no hook we could reuse for the reactor extension. I opened a feature request: https://app.camunda.com/jira/browse/CAM-10833

Once this exists in the engine, we can reopen this issue.
